// THE ANALYSIS MODEL — one dbt Python model per query call, running every analysis of the call in
// one pass (one cold start of the warehouse runtime for all of them). Its body is this server's
// python/retentioneering_model.py, inlined — on BigQuery the model runs as a notebook on the
// warehouse runtime (Colab Enterprise, via bigframes), where no module of ours can be imported —
// followed by the caller's analyses as a JSON literal and the model function. No code of the
// caller's reaches it: the spec is data, validated against the tool schema first.

import { readFileSync } from 'node:fs';
import { assetPath, missingAssetMessage } from '../runtime-assets.js';
import { pyLiteral } from '../python-model.js';
import { retentioneeringFacts } from './schema.js';

let body;
function moduleBody() {
  if (body === undefined) {
    const file = assetPath('retentioneeringModel');
    if (!file) throw new Error(missingAssetMessage('retentioneeringModel'));
    body = readFileSync(file, 'utf8');
  }
  return body;
}

/**
 * The dbt.config of an analysis model on this warehouse. DuckDB runs it in the dbt process itself
 * (the feature's dbt environment has the library). A warehouse runtime (bigframes → Colab
 * Enterprise, Dataproc) gets the library installed by dbt at run time, at the version this server
 * pins, plus whatever the operator pins (MCP_RETENTIONEERING_MODEL_CONFIG — a runtime template, a
 * timeout); the operator's keys win.
 */
export function analysisModelConfig(catalog, operatorConfig = {}) {
  const method = catalog.pythonRuntime?.method || null;
  const remote = catalog.dialect !== 'duckdb';
  return {
    materialized: 'table',
    ...(remote && method ? { submission_method: method } : {}),
    ...(remote ? { packages: [`retentioneering==${retentioneeringFacts().version}`] } : {}),
    ...operatorConfig,
  };
}

/** The Python source of the analysis model over `inputModel`. */
export function compileAnalysisModel({ inputModel, spec, config }) {
  const cfgArgs = Object.entries(config).map(([k, v]) => `${k}=${pyLiteral(v)}`).join(', ');
  return [
    '# Generated by the retentioneering feature of this server — python/retentioneering_model.py',
    '# inlined, then the analyses of one query call. Do not edit: a new call writes a new model.',
    moduleBody(),
    '',
    `SPEC = ${pyLiteral(spec)}`,
    '',
    '',
    'def model(dbt, session):',
    `    dbt.config(${cfgArgs})`,
    `    return run(dbt.ref(${pyLiteral(inputModel)}), SPEC)`,
    '',
  ].join('\n');
}
