// THE PYTHON MODELS — one per query call, running every analysis of the call in one pass (one cold
// start of the warehouse runtime for all of them), and one per materialize of an eventstream draft
// whose steps are the library's (the eventstream after them, stored as a table the analyses read). Its body is this server's
// python/retentioneering_model.py, inlined — on BigQuery the model runs as a notebook on the
// warehouse runtime (Colab Enterprise, via bigframes), where no module of ours can be imported —
// followed by the caller's analyses as a JSON literal and the model function. No code of the
// caller's reaches it: the spec is data, validated against the tool schema first.

import { readFileSync } from 'node:fs';
import { assetPath, missingAssetMessage } from '../runtime-assets.js';
import { pyLiteral } from '../python-model.js';
import { retentioneeringFacts } from './schema.js';

let body;
function moduleBody() {
  if (body === undefined) {
    const file = assetPath('retentioneeringModel');
    if (!file) throw new Error(missingAssetMessage('retentioneeringModel'));
    body = readFileSync(file, 'utf8');
  }
  return body;
}

/**
 * The dbt.config of an analysis model on this warehouse. DuckDB runs it in the dbt process itself
 * (the feature's dbt environment has the library). A warehouse runtime (bigframes → Colab
 * Enterprise, Dataproc) gets the library at the version this server pins from the model itself
 * (ensure_library, python/retentioneering_model.py) rather than from dbt's `packages`: dbt's
 * installer keeps pip's output to itself when pip fails, so its failure said nothing. Whatever the
 * operator pins (MCP_RETENTIONEERING_MODEL_CONFIG — a runtime template, a timeout) is added; the
 * operator's keys win.
 */
export function analysisModelConfig(catalog, operatorConfig = {}) {
  const method = catalog.pythonRuntime?.method || null;
  const remote = catalog.dialect !== 'duckdb';
  return {
    materialized: 'table',
    ...(remote && method ? { submission_method: method } : {}),
    ...operatorConfig,
  };
}

/** The library as this server pins it — what ensure_library makes importable on the runtime. */
export const libraryRequirement = () => `retentioneering==${retentioneeringFacts().version}`;

/** A model over `inputModel` that returns `call(source, SPEC)` of python/retentioneering_model.py. */
function compile({ inputModel, spec, config, call, what }) {
  const cfgArgs = Object.entries(config).map(([k, v]) => `${k}=${pyLiteral(v)}`).join(', ');
  return [
    '# Generated by the retentioneering feature of this server — python/retentioneering_model.py',
    `# inlined, then ${what}. Do not edit: a new call writes a new model.`,
    moduleBody(),
    '',
    `SPEC = ${pyLiteral(spec)}`,
    '',
    '',
    'def model(dbt, session):',
    `    dbt.config(${cfgArgs})`,
    `    ensure_library(${pyLiteral(libraryRequirement())})`,
    `    source = dbt.ref(${pyLiteral(inputModel)})`,
    `    return to_runtime(${call}(source, SPEC), source, session)`,
    '',
  ].join('\n');
}

/** The Python source of the analysis model over `inputModel`: every analysis of one query call. */
export function compileAnalysisModel({ inputModel, spec, config }) {
  return compile({ inputModel, spec, config, call: 'run', what: 'the analyses of one query call' });
}

/** The Python source of the model that materializes a draft's library steps over `inputModel`: the
 *  eventstream after them, as rows again (python/retentioneering_model.py apply_steps). */
export function compileStepsModel({ inputModel, spec, config }) {
  return compile({ inputModel, spec, config, call: 'apply_steps', what: 'the library steps of one eventstream draft' });
}
