#!/usr/bin/env python3
"""The facts the retentioneering feature states about the library — EXTRACTED from it, never
written from its prose (CLAUDE.md: a fact about an external library is generated from that library).

What the feature's tool schemas offer (the analyses and their parameters, the edge weights of the
transition graph, the path metrics a cluster or segment analysis takes and how each rolls up, the
clustering methods, the anchor options) is read HERE from the installed package and written to
config/retentioneering-facts.json; src/retentioneering/ renders every enum and default from that
sheet, and test/unit/retentioneering-facts.test.js holds the schemas to it.

    .venvs/retentioneering/bin/python scripts/retentioneering-facts.py --write   # regenerate
    .venvs/retentioneering/bin/python scripts/retentioneering-facts.py --check   # exit 1 if stale

The interpreter is the feature's own dbt environment (npm run dbt:env -- create retentioneering):
the library whose facts are written is the one the analyses run on.
"""

import inspect
import json
import os
import sys
import typing
from datetime import date
from importlib import metadata

os.environ.setdefault("RETENTIONEERING_NO_TRACK", "1")

from retentioneering import Eventstream  # noqa: E402
from retentioneering.metrics import metric_builder  # noqa: E402
from retentioneering.paths import anchors  # noqa: E402
from retentioneering.tools import segment_overview, cluster_analysis  # noqa: E402
from retentioneering.utils import clustering_methods  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "config", "retentioneering-facts.json")

# The headless analyses the feature runs: each widget's `*_data` twin (step matrix and step sankey
# share one — step_matrix_data is its alias).
DATA_FUNCTIONS = ["transition_graph_data", "step_sankey_data", "funnel_data", "cluster_analysis_data", "segment_overview_data"]


def literal_choices(annotation):
    """The values of a Literal[...] annotation (also inside an Optional/Union), else None."""
    if typing.get_origin(annotation) is typing.Literal:
        return list(typing.get_args(annotation))
    for arg in typing.get_args(annotation) or ():
        found = literal_choices(arg)
        if found:
            return found
    return None


def plain(value):
    if value is inspect.Parameter.empty:
        return None
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return repr(value)


def signature_of(name):
    sig = inspect.signature(getattr(Eventstream, name), eval_str=True)
    params = []
    for p in sig.parameters.values():
        if p.name == "self":
            continue
        entry = {"name": p.name, "required": p.default is inspect.Parameter.empty}
        if p.default is not inspect.Parameter.empty:
            entry["default"] = plain(p.default)
        choices = literal_choices(p.annotation)
        if choices:
            entry["choices"] = choices
        params.append(entry)
    return params


def build():
    signatures = {name: signature_of(name) for name in DATA_FUNCTIONS}
    edge = next(p for p in signatures["transition_graph_data"] if p["name"] == "edge_weight")
    return {
        "library": "retentioneering",
        "note": "Generated by scripts/retentioneering-facts.py from the installed library — do not hand-edit.",
        "version": metadata.version("retentioneering"),
        "generated_on": date.today().isoformat(),
        "data_functions": signatures,
        "edge_weights": edge["choices"],
        "path_metrics": sorted(metric_builder.VALID_METRICS),
        "in_segment_modes": sorted(metric_builder.IN_SEGMENT_MODES),
        "synthetic_events": sorted(metric_builder.SYNTHETIC_EVENTS),
        "segment_aggs": sorted(segment_overview.AGG_FUNCTIONS) + ["complement_distance"],
        "cluster_methods": list(typing.get_args(cluster_analysis.T_ClusteringMethod)),
        "cluster_method_args": {m: sorted(keys) for m, keys in clustering_methods.METHOD_ARGS.items()},
        "cluster_scalers": [s for s in typing.get_args(typing.get_args(cluster_analysis.T_Scaler)[0])] if typing.get_args(cluster_analysis.T_Scaler) else [],
        "anchor_keys": sorted(anchors.SPEC_KEYS),
        "anchor_occurrences": list(anchors.OCCURRENCES),
    }


def normalized(facts):
    return {k: v for k, v in facts.items() if k != "generated_on"}


def main(argv):
    facts = build()
    if "--check" in argv:
        try:
            with open(OUT, encoding="utf-8") as f:
                current = json.load(f)
        except FileNotFoundError:
            print(f"{OUT} is missing", file=sys.stderr)
            return 1
        if normalized(current) != normalized(facts):
            print(f"{OUT} is stale for retentioneering {facts['version']} — regenerate with --write", file=sys.stderr)
            return 1
        print(f"{OUT} matches retentioneering {facts['version']}")
        return 0
    if "--write" in argv:
        with open(OUT, "w", encoding="utf-8") as f:
            json.dump(facts, f, indent=2, sort_keys=False)
            f.write("\n")
        print(f"wrote {OUT} (retentioneering {facts['version']})")
        return 0
    json.dump(facts, sys.stdout, indent=2)
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
