// Header comment prepended to every generated SQL model, recording the exact
// declarative config (as YAML) the SQL was generated from — so a generated dbt
// model is self-documenting and traceable back to its tool inputs.

import yaml from 'js-yaml';
import { inertText } from './jinja-inert.js';

/** A `/* ... *​/` banner embedding the source config as YAML. */
export function sqlConfigHeader(kind, config) {
  let body;
  try {
    body = yaml.dump(config ?? {}, { lineWidth: 100, noRefs: true, skipInvalid: true });
  } catch {
    body = String(config);
  }
  // The config is arbitrary caller text (a filter literal, a python function body). A `*/` inside it
  // would CLOSE this banner early and leave the rest of the YAML to be parsed as SQL; a `/*` would
  // OPEN a nested comment on the engines that nest them (Postgres does, BigQuery does not) and the
  // banner would then swallow the model. SQL has no escape inside a block comment, so both markers
  // are broken up with a backslash — the banner is documentation, and it still reads as declared.
  // dbt renders the whole .sql file as Jinja, comments included: a `{{ … }}` in the config would
  // be EVALUATED at build time, so every Jinja opener is broken too (jinja-inert.js).
  const safe = inertText(body.replace(/\*\//g, '*\\/').replace(/\/\*/g, '/\\*'));
  const indented = safe.split('\n').map((l) => (l ? `  ${l}` : l)).join('\n');
  return `/*\n  Generated by bi-analytical-mcp (${kind}) from config:\n${indented}*/\n`;
}
