// Header comment prepended to every generated SQL model, recording the exact
// declarative config (as YAML) the SQL was generated from — so a generated dbt
// model is self-documenting and traceable back to its tool inputs.

import yaml from 'js-yaml';

/** A `/* ... *​/` banner embedding the source config as YAML. */
export function sqlConfigHeader(kind, config) {
  let body;
  try {
    body = yaml.dump(config ?? {}, { lineWidth: 100, noRefs: true, skipInvalid: true });
  } catch {
    body = String(config);
  }
  const indented = body.split('\n').map((l) => (l ? `  ${l}` : l)).join('\n');
  return `/*\n  Generated by bi-analytical-mcp (${kind}) from config:\n${indented}*/\n`;
}
